######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 15 11:06:39 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += spread_batch.h
FORMS += spread_batch.ui
SOURCES += spread_batch.cpp spread_main.cpp
