######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 21:12:56 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += maxload_batch.h
FORMS += maxload_batch.ui
SOURCES += maxload_batch.cpp maxload_main.cpp
